"""empty message

Revision ID: 035f6b799215
Revises: 
Create Date: 2024-11-22 19:59:12.380144

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '035f6b799215'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documento_empleado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_documento', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('empleado_dni', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['empleado_dni'], ['empleados.dni'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('caballo_tipoja',
    sa.Column('caballo_id', sa.Integer(), nullable=False),
    sa.Column('JYA_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['JYA_id'], ['JYA.id'], ),
    sa.ForeignKeyConstraint(['caballo_id'], ['caballos.id'], ),
    sa.PrimaryKeyConstraint('caballo_id', 'JYA_id')
    )
    with op.batch_alter_table('JYA', schema=None) as batch_op:
        batch_op.add_column(sa.Column('caballo_id', sa.Integer(), nullable=True))
        batch_op.alter_column('edad',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('telefono_actual',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('contacto_emergencia',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
        batch_op.alter_column('becado',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('propuesta_trabajo',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('condicion_trabajo',
               existing_type=postgresql.ENUM('REGULAR', 'DE BAJA', name='condicion_trabajo'),
               nullable=False)
        batch_op.alter_column('sede',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.create_foreign_key(None, 'caballos', ['caballo_id'], ['id'])

    with op.batch_alter_table('empleados', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('publicaciones', schema=None) as batch_op:
        batch_op.alter_column('autor_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publicaciones', schema=None) as batch_op:
        batch_op.alter_column('autor_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('empleados', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('JYA', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('sede',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('condicion_trabajo',
               existing_type=postgresql.ENUM('REGULAR', 'DE BAJA', name='condicion_trabajo'),
               nullable=True)
        batch_op.alter_column('propuesta_trabajo',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('becado',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('contacto_emergencia',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
        batch_op.alter_column('telefono_actual',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('edad',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('caballo_id')

    op.drop_table('caballo_tipoja')
    op.drop_table('documento_empleado')
    # ### end Alembic commands ###
