"""empty message

Revision ID: 0c4e07822f98
Revises: 
Create Date: 2024-10-24 11:18:06.675204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c4e07822f98'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('JYA', schema=None) as batch_op:
        batch_op.add_column(sa.Column('debts', sa.Boolean(), nullable=True))

    with op.batch_alter_table('documentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre_documento', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('jya_dni', sa.String(length=20), nullable=False))
        batch_op.alter_column('caballo_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'JYA', ['jya_dni'], ['dni'])
        batch_op.drop_column('nombre')

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'JYA', ['j_a'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('documentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('caballo_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('jya_dni')
        batch_op.drop_column('created_at')
        batch_op.drop_column('nombre_documento')

    with op.batch_alter_table('JYA', schema=None) as batch_op:
        batch_op.drop_column('debts')

    # ### end Alembic commands ###
