"""empty message

Revision ID: 2890cd80a8c7
Revises: 0c4e07822f98
Create Date: 2024-11-03 20:11:17.361657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2890cd80a8c7'
down_revision = '0c4e07822f98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('caballos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_ja_asignado', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('caballos', schema=None) as batch_op:
        batch_op.drop_column('tipo_ja_asignado')

    # ### end Alembic commands ###
