"""empty message

Revision ID: 2ddbaa28014b
Revises: 
Create Date: 2024-10-20 02:33:41.307768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ddbaa28014b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pago',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('beneficiario_id', sa.Integer(), nullable=True),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('fecha_pago', sa.Date(), nullable=True),
    sa.Column('tipo_pago', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['beneficiario_id'], ['empleados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('beneficiary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pago_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'pago', ['pago_id'], ['id'])
        batch_op.drop_column('Pago_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('beneficiary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Pago_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('pago_id')

    op.drop_table('pago')
    # ### end Alembic commands ###
