"""empty message

Revision ID: a89530ed9674
Revises: f014e5fc437c
Create Date: 2024-10-19 14:26:41.114908

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a89530ed9674'
down_revision = 'f014e5fc437c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('JYA',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('dni', sa.String(length=20), nullable=False),
    sa.Column('edad', sa.Integer(), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('lugar_nacimiento', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('domicilio_actual', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('telefono_actual', sa.String(length=20), nullable=True),
    sa.Column('contacto_emergencia', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('becado', sa.Boolean(), nullable=True),
    sa.Column('porcentaje_beca', sa.Float(), nullable=True),
    sa.Column('profesionales_atendiendo', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dni')
    )
    with op.batch_alter_table('caballo_tipoja', schema=None) as batch_op:
        batch_op.add_column(sa.Column('JYA_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'JYA', ['JYA_id'], ['id'])
        batch_op.drop_column('tipoja_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('caballo_tipoja', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipoja_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('JYA_id')

    op.drop_table('JYA')
    # ### end Alembic commands ###
