"""Initial migration.

Revision ID: bce3c478986b
Revises: 
Create Date: 2024-10-13 23:34:23.499218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bce3c478986b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('caballos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('sexo', sa.String(length=50), nullable=False),
    sa.Column('raza', sa.String(length=255), nullable=True),
    sa.Column('pelaje', sa.String(length=255), nullable=True),
    sa.Column('tipo_ingreso', sa.String(length=50), nullable=False),
    sa.Column('fecha_ingreso', sa.Date(), nullable=False),
    sa.Column('sede_asignada', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('j_a', sa.Integer(), nullable=True),
    sa.Column('pay_date', sa.Date(), nullable=True),
    sa.Column('payment_method', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('recipient', sa.Integer(), nullable=True),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('miembros_equipo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipos_ja',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('caballo_conductores',
    sa.Column('caballo_id', sa.Integer(), nullable=False),
    sa.Column('miembroequipo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['caballo_id'], ['caballos.id'], ),
    sa.ForeignKeyConstraint(['miembroequipo_id'], ['miembros_equipo.id'], ),
    sa.PrimaryKeyConstraint('caballo_id', 'miembroequipo_id')
    )
    op.create_table('caballo_entrenadores',
    sa.Column('caballo_id', sa.Integer(), nullable=False),
    sa.Column('miembroequipo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['caballo_id'], ['caballos.id'], ),
    sa.ForeignKeyConstraint(['miembroequipo_id'], ['miembros_equipo.id'], ),
    sa.PrimaryKeyConstraint('caballo_id', 'miembroequipo_id')
    )
    op.create_table('caballo_tipoja',
    sa.Column('caballo_id', sa.Integer(), nullable=False),
    sa.Column('tipoja_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['caballo_id'], ['caballos.id'], ),
    sa.ForeignKeyConstraint(['tipoja_id'], ['tipos_ja.id'], ),
    sa.PrimaryKeyConstraint('caballo_id', 'tipoja_id')
    )
    op.create_table('documentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('tipo_documento', sa.String(length=255), nullable=False),
    sa.Column('archivo_url', sa.String(length=255), nullable=True),
    sa.Column('caballo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['caballo_id'], ['caballos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documentos')
    op.drop_table('caballo_tipoja')
    op.drop_table('caballo_entrenadores')
    op.drop_table('caballo_conductores')
    op.drop_table('tipos_ja')
    op.drop_table('miembros_equipo')
    op.drop_table('invoices')
    op.drop_table('caballos')
    # ### end Alembic commands ###
