"""empty message

Revision ID: c0c58ff3f028
Revises: bce3c478986b
Create Date: 2024-10-15 19:28:48.381013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0c58ff3f028'
down_revision = 'bce3c478986b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('caballo_conductores')
    op.drop_table('caballo_entrenadores')
    op.drop_table('caballo_tipoja')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('caballo_tipoja',
    sa.Column('caballo_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tipoja_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['caballo_id'], ['caballos.id'], name='caballo_tipoja_caballo_id_fkey'),
    sa.ForeignKeyConstraint(['tipoja_id'], ['tipos_ja.id'], name='caballo_tipoja_tipoja_id_fkey'),
    sa.PrimaryKeyConstraint('caballo_id', 'tipoja_id', name='caballo_tipoja_pkey')
    )
    op.create_table('caballo_entrenadores',
    sa.Column('caballo_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('miembroequipo_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['caballo_id'], ['caballos.id'], name='caballo_entrenadores_caballo_id_fkey'),
    sa.ForeignKeyConstraint(['miembroequipo_id'], ['miembros_equipo.id'], name='caballo_entrenadores_miembroequipo_id_fkey'),
    sa.PrimaryKeyConstraint('caballo_id', 'miembroequipo_id', name='caballo_entrenadores_pkey')
    )
    op.create_table('caballo_conductores',
    sa.Column('caballo_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('miembroequipo_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['caballo_id'], ['caballos.id'], name='caballo_conductores_caballo_id_fkey'),
    sa.ForeignKeyConstraint(['miembroequipo_id'], ['miembros_equipo.id'], name='caballo_conductores_miembroequipo_id_fkey'),
    sa.PrimaryKeyConstraint('caballo_id', 'miembroequipo_id', name='caballo_conductores_pkey')
    )
    # ### end Alembic commands ###
