"""empty message

Revision ID: e398518b3616
Revises: 2890cd80a8c7
Create Date: 2024-11-03 20:36:46.714235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e398518b3616'
down_revision = '2890cd80a8c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('caballo_tipoja')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('caballo_tipoja',
    sa.Column('caballo_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('JYA_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['JYA_id'], ['JYA.id'], name='caballo_tipoja_JYA_id_fkey'),
    sa.ForeignKeyConstraint(['caballo_id'], ['caballos.id'], name='caballo_tipoja_caballo_id_fkey'),
    sa.PrimaryKeyConstraint('caballo_id', 'JYA_id', name='caballo_tipoja_pkey')
    )
    # ### end Alembic commands ###
