[tool.poetry]
name = "web"
version = "0.1.0"
description = ""
authors = ["sofiacelano <sofia.celano181928@alumnos.info.unlp.edu.ar>"]
readme = "README.md"
packages = [{include = "web", from = "src"}]

[tool.poetry.dependencies]
python = "^3.12.3"
flask = "^3.0.3"
psycopg2-binary = "^2.9.9"
flask-sqlalchemy = "^3.1.1"
flask-bcrypt = "^1.0.1"
<<<<<<< HEAD
minio = "^7.2.9"
=======
flask-migrate = "^4.0.7"
>>>>>>> 8fee9b7a120b35b621612a353d27f36a3cdd3462


[tool.poetry.group.dev.dependencies]
pytest = "^8.3.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
